apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-policy-webhook.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-policy-webhook.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{ toYaml .Values.policy | indent 4 }}
