{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-policy-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-policy-webhook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-policy-webhook.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressPodSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: https
{{- end }}
