apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-policy-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-policy-webhook.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "k8s-policy-webhook.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
